command /server:
    permission: serveur.menu
    permission message: "&cVous n'avez pas la permission d'utiliser cette commande."
    trigger:
        open chest inventory with 3 rows named "&6&lSelection du Mode de Jeu" to player
        wait 1 tick

        # Koh-Lanta (Feu de camp)
        set slot 10 of player's current inventory to campfire named "&e&lKoh-Lanta" with lore "&7Clique pour rejoindre"

        # Ninja Warrior (Barriere de fer pour l'obstacle)
        set slot 12 of player's current inventory to iron bars named "&b&lNinja Warrior" with lore "&7Clique pour rejoindre"

        # Tournois PVP (Epee en diamant)
        set slot 14 of player's current inventory to diamond sword named "&c&lTournois PVP" with lore "&7Clique pour rejoindre"

        # Hickabrain (Tete de joueur)
        set slot 16 of player's current inventory to player head named "&d&lHickabrain" with lore "&7Clique pour rejoindre"

        # The Platform (Bloc de pierre pour la plateforme)
        set slot 20 of player's current inventory to stone named "&7&lThe Platform" with lore "&7Clique pour rejoindre"

        # Retour au Lobby (Lit rouge)
        set slot 24 of player's current inventory to red bed named "&6&lRetour au Lobby" with lore "&7Clique pour revenir au lobby"

on inventory click:
    if name of event-inventory is "&6&lSelection du Mode de Jeu":
        cancel event
        if index of event-slot is 10:
            execute console command "lp user %player% parent clear"
            wait 1 tick
            execute player command "mvtp world"
            execute console command "lp user %player% parent set KohLanta"
        if index of event-slot is 12:
            execute console command "lp user %player% parent clear"
            wait 1 tick
            execute player command "mvtp Ninja_Warrior"
            execute console command "lp user %player% parent set Ninja_Warrior"
        if index of event-slot is 14:
            execute console command "lp user %player% parent clear"
            wait 1 tick
            execute player command "mvtp PVP2"
            execute console command "lp user %player% parent set PVP"
        if index of event-slot is 16:
            execute console command "lp user %player% parent clear"
            wait 1 tick
            execute player command "mvtp Hickabrain"
            execute console command "lp user %player% parent set hickabrain"
        if index of event-slot is 20:
            execute console command "lp user %player% parent clear"
            wait 1 tick
            execute player command "mvtp The_Platform"
            execute console command "lp user %player% parent set The_Platform"
        if index of event-slot is 24:
            execute console command "lp user %player% parent clear"
            wait 1 tick
            execute player command "spawn %player%"
            execute console command "lp user %player% parent set default" # Commande pour retourner au lobby et mettre le rôle par défaut