name: CI-SFTP

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: gohstcamera.541eb4c2
          server: 9042.mystrator.com
          port: 2022
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: ./*
          remote_path: /var/www
          args: '-o ConnectTimeout=5'
